
name: monoidal-map

default-extensions:
- LambdaCase
- BlockArguments
- OverloadedRecordDot
- DefaultSignatures
- DerivingStrategies
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- NoFieldSelectors
- UndecidableInstances
- ViewPatterns

language: GHC2021

dependencies:
- base
- containers
- hashable
- unordered-containers

ghc-options: -freverse-errors

library:
  source-dirs:
  - src